---
title: 'PPG'
repo-actions: false
---

## Intro
Biometry subsystem provides functions to access PPG functionality.

## Prerequisites
1) Teslasuit API Initialization
The Teslasuit API must be initialized before accessing any of its features.
2) Connected Teslasuit Device
A Teslasuit device must be connected. If no device is available, the system will wait until one is attached.
3) Access to the PPG Subsystem
The TsPPG class is part of the device's functionality and can only be used after obtaining access to a connected Teslasuit device.

### Note: 
Since TsPPG is a member of the device class, it cannot be used independently without an active Teslasuit device.

## Class TsPpg

Handles PPG (Photoplethysmography) sensor data processing and streaming.
This class manages the interaction with a PPG sensor, including raw and processed data streaming, calibration, and retrieving heart rate variability (HRV) and raw PPG data.

Class methods:


```python
start_raw_streaming(self)
```
Start the streaming of a PPG raw data

```python
stop_raw_streaming(self)
```
Stop the streaming of a PPG raw data

```python
get_hrv_data_on_ready(self)
```
Blocks execution until HRV data is ready and returns the latest HRV data.

Returns [TsHrv](../core/data_structures.qmd#tshrv) (struct): The latest HRV data.

```python
get_raw_data_on_ready(self)
```
Blocks execution until raw PPG data is ready and returns the latest raw data.
Returns TsPpgRawData (struct): The latest raw PPG data.

```python
get_hrv(self)
```
Retrieves the latest HRV data.
Returns [TsHrv](../core/data_structures.qmd#tshrv) (struct): The latest HRV data.

```python
get_data(self)
```
Retrieves the latest raw PPG data.
Returns TsPpgRawData (struct): The latest raw PPG data.

```python
get_data(self)
```
Calibrates PPG processor.
The calibration procedure is capturing interval of the raw data during 3 seconds. 
The captured interval will be used in calculation of all ppg parameters.
By default, calibration procedure starts on starting PPG processor.
In case on bad start, the calibration procedure might be restarted using this function.